spring:
  application:
    name: codesync
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
app:
  jjwt:
    secret: ${JWT_SECRET_KEY}
    duration: 7200000 # 2 hour